server:
  port: 8088

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      default-zone: http://registry-service:8761/eureka
    instance:
      hostname: registry-service
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: micro01-client
          uri: lb://micro01-client
          predicates:
            - Path=/api/v1/client/**
