server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bank
          uri: lb://bank
          predicates:
            - Path=/product/**
        - id: client
          uri: lb://client
          predicates:
            - Path=/client/**
