server:
  port: 8088

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: micro01-client
          uri: http://localhost:8091/
          predicates:
            - Path=/api/v1/client/**
