spring:
  profiles:
    active: cloud
    
spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: registry-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://registry-service/eureka/
